server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          enabled: true
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000

services:
  user-service:
    url: http://localhost:${USER_SERVICE_PORT:8082}
    internal-api-key: ${USER_SERVICE_INTERNAL_API_KEY:UserInternalKey_SuperSecret_123456}

app:
  security:
    jwt:
      secret: mySuperUltraSecureSecretKeyThatMustBeLongEnough123456
      expiration: 86400000
      public-paths:
        - /api/auth/login
        - /api/auth/refresh
        - /api/auth/logout
        - /swagger-ui/**
        - /v3/api-docs/**
        - /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    com.orderprocessing.authservice.client.UserServiceClient: DEBUG


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
