server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: user-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USERNAME:postgres_user1234}
    password: ${DB_PASSWORD:passwordpostgres1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: UserServiceHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  security:
    jwt:
      secret: mySuperUltraSecureSecretKeyThatMustBeLongEnough123456
      expiration: 3600000
      public-paths:
        - /swagger-ui/**
        - /v3/api-docs/**
        - /swagger-ui.html
    internal:
      api-key: ${USER_SERVICE_INTERNAL_API_KEY:UserInternalKey_SuperSecret_123456}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO
    org.springframework.security: DEBUG