kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    order-events: order.events
    order-events-partitions: 3
    order-events-replicas: 1
    store-events: store.events
    store-events-partitions: 3
    store-events-replicas: 1